language: scala
scala:
  - 2.10.4
  - 2.11.5

sudo: required
services:
  - docker

before_install:
  - git fetch --tags
  - openssl aes-256-cbc -K $encrypted_f80571800bec_key -iv $encrypted_f80571800bec_iv -in .credentials.enc -out .credentials -d
  - mkdir -p $HOME/.bintray
  - cp .credentials $HOME/.bintray/.credentials
  - docker-compose up -d
  - docker-compose ps

after_install:
  - docker-compose stop

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    - sbt ++$TRAVIS_SCALA_VERSION publish
  fi
