etcd-server1:
  image: quay.io/coreos/etcd
  environment:
    ETCD_NAME: "default"
    ETCD_ADVERTISE_CLIENT_URLS: "http://172.17.0.2:2379,http://172.17.0.2:4001"
    ETCD_INITAL_ADVERTISE_PEER_URLS: "http://172.17.0.2:2379,http://172.17.0.2:4001"
    ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380,http://0.0.0.0:7001"
  ports:
    - "4001:4001"
    - "7001:7001"
    - "2379:2379"
    - "2380:2380"

etcd-server2:
  image: quay.io/coreos/etcd
  environment:
    ETCD_NAME: "peer"
    ETCD_PROXY: "on"
    ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380,http://0.0.0.0:7001"
    ETCD_INITIAL_CLUSTER: "default=http://172.17.0.2:2380,peer=http://172.17.0.3:2380"
    ETCD_INITIAL_CLUSTER_STATE: "existing"
  ports:
    - "4002:4001"
    - "7002:7001"
    - "2479:2379"
    - "2480:2380"